name: DL23
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pip
  - matplotlib
  - numpy
  - jupyterlab
  - pytorch
  - torchvision
  - opencv
  - pillow
  - scikit-learn
  - gdown
  - urllib3
