name: DL23
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.18
  - pip
  - matplotlib
  - numpy
  - jupyterlab
  - pytorch=2.1.1
  - torchvision=0.16.1
  - opencv
  - pillow
  - scikit-learn
  - gdown
  - urllib3
